In [ ]:
import numpy as np
import pandas as pd
from pathlib import Path
import plotly.graph_objs as go

# Path configuration

In [ ]:
projectRoot = Path.cwd().parents[1]
projectRoot

In [ ]:
dataPath = Path(projectRoot, 
                "data/tlc_trip_record/yellow") # Replace with the path of your data
dataPath

# Load Data

In [4]:
baseName = "yellow_tripdata_"

In [5]:
data = pd.DataFrame()

In [6]:
years = range(2024,2026,1)
for year in years:
    print(year, end= ", ")

2024, 2025,

In [7]:
months = [ f"{m:02d}" for m in range(1,13,1)]
months

['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12']

In [ ]:
# WARNING, the data might be too big to fit into memory
# a year of yellow tlc data is around 5.7 GB 
for year in years:
    for month in months:
        filePath = Path(dataPath, baseName + f"{year}-{month}.parquet") 
        try:
            d = pd.read_parquet(filePath)
        except FileNotFoundError:
            print(f"File {filePath} doesn't exist")
            continue
        data = pd.concat([data,d])

# Analysing

In [9]:
data

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
0,2,2024-01-01 00:57:55,2024-01-01 01:17:43,1.0,1.72,1.0,N,186,79,2,17.70,1.0,0.5,0.00,0.0,1.0,22.70,2.5,0.0
1,1,2024-01-01 00:03:00,2024-01-01 00:09:36,1.0,1.80,1.0,N,140,236,1,10.00,3.5,0.5,3.75,0.0,1.0,18.75,2.5,0.0
2,1,2024-01-01 00:17:06,2024-01-01 00:35:01,1.0,4.70,1.0,N,236,79,1,23.30,3.5,0.5,3.00,0.0,1.0,31.30,2.5,0.0
3,1,2024-01-01 00:36:38,2024-01-01 00:44:56,1.0,1.40,1.0,N,79,211,1,10.00,3.5,0.5,2.00,0.0,1.0,17.00,2.5,0.0
4,1,2024-01-01 00:46:51,2024-01-01 00:52:57,1.0,0.80,1.0,N,211,148,1,7.90,3.5,0.5,3.20,0.0,1.0,16.10,2.5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3668366,2,2024-12-31 23:32:00,2024-12-31 23:56:00,NaN,10.71,NaN,NaN,16,7,0,-4.13,0.0,0.5,0.00,0.0,1.0,-2.63,NaN,NaN
3668367,2,2024-12-31 23:05:00,2024-12-31 23:18:00,NaN,4.56,NaN,NaN,252,16,0,-1.68,0.0,0.5,0.00,0.0,1.0,-0.18,NaN,NaN
3668368,2,2024-12-31 23:03:16,2024-12-31 23:28:35,NaN,3.94,NaN,NaN,181,255,0,4.46,0.0,0.5,5.19,0.0,1.0,11.15,NaN,NaN
3668369,1,2024-12-31 23:15:33,2024-12-31 23:36:29,NaN,4.20,NaN,NaN,165,61,0,27.07,0.0,0.5,0.00,0.0,1.0,28.57,NaN,NaN
3668370,2,2024-12-31 23:04:36,2024-12-31 23:33:34,NaN,5.76,NaN,NaN,225,114,0,2.17,0.0,0.5,0.00,0.0,1.0,6.17,NaN,NaN

In [10]:
data.columns

Index(['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime',
       'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag',
       'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra',
       'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge',
       'total_amount', 'congestion_surcharge', 'Airport_fee'],
      dtype='str')

In [11]:
# VendorID toma solo 4 valores??
data["VendorID"].unique()

array([2, 1, 6, 7], dtype=int32)

In [45]:
data.describe()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
count,4.116972e+07,41169720,41169720,3.707849e+07,4.116972e+07,3.707849e+07,4.116972e+07,4.116972e+07,4.116972e+07,4.116972e+07,4.116972e+07,4.116972e+07,4.116972e+07,4.116972e+07,4.116972e+07,4.116972e+07,3.707849e+07,3.707849e+07
mean,1.764232e+00,2024-07-06 10:01:25.051412,2024-07-06 10:18:53.125903,1.333931e+00,4.976101e+00,2.322150e+00,1.642428e+02,1.634475e+02,1.107259e+00,1.926851e+01,1.385953e+00,4.797774e-01,3.307884e+00,5.615266e-01,9.629934e-01,2.783281e+01,2.232144e+00,1.470060e-01
min,1.000000e+00,2002-12-31 16:46:07,2002-12-31 17:24:07,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,-2.261200e+03,-9.250000e+00,-5.000000e-01,-3.000000e+02,-1.406300e+02,-1.000000e+00,-2.265450e+03,-2.500000e+00,-1.750000e+00
25%,2.000000e+00,2024-04-06 20:07:27.500000,2024-04-06 20:23:52,1.000000e+00,1.010000e+00,1.000000e+00,1.320000e+02,1.130000e+02,1.000000e+00,9.300000e+00,0.000000e+00,5.000000e-01,0.000000e+00,0.000000e+00,1.000000e+00,1.575000e+01,2.500000e+00,0.000000e+00
50%,2.000000e+00,2024-07-03 23:35:15,2024-07-03 23:50:35,1.000000e+00,1.760000e+00,1.000000e+00,1.610000e+02,1.620000e+02,1.000000e+00,1.350000e+01,1.000000e+00,5.000000e-01,2.600000e+00,0.000000e+00,1.000000e+00,2.100000e+01,2.500000e+00,0.000000e+00
75%,2.000000e+00,2024-10-08 17:33:35,2024-10-08 17:53:27.250000,1.000000e+00,3.360000e+00,1.000000e+00,2.330000e+02,2.340000e+02,1.000000e+00,2.260000e+01,2.500000e+00,5.000000e-01,4.250000e+00,0.000000e+00,1.000000e+00,3.060000e+01,2.500000e+00,0.000000e+00
max,7.000000e+00,2026-06-26 23:53:12,2026-06-27 20:59:10,9.000000e+00,3.986086e+05,9.900000e+01,2.650000e+02,2.650000e+02,5.000000e+00,3.355444e+05,6.599000e+01,4.130000e+01,9.999900e+02,1.702880e+03,2.000000e+00,3.355509e+05,2.520000e+00,1.750000e+00
std,4.258568e-01,NaN,NaN,8.158242e-01,4.192305e+02,1.092805e+01,6.434069e+01,6.960009e+01,6.515108e-01,7.671984e+01,1.815878e+00,1.301830e-01,4.090523e+00,2.240545e+00,2.550554e-01,7.805359e+01,8.746528e-01,5.020407e-01